<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EPPlus" Version="8.7.1" />
    <PackageVersion Include="ErrorOr" Version="2.1.1" />
    <PackageVersion Include="FreeSpire.XLS" Version="16.4.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageVersion Include="PDFtoImage" Version="5.4.0" />
    <PackageVersion Include="PhotoSauce.MagicScaler" Version="0.15.0" />
    <PackageVersion Include="PhotoSauce.NativeCodecs.Libwebp" Version="1.6.0-preview1" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.9" />
  </ItemGroup>
</Project>